version: "3.9"

services:
  cheap-delivery:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: cheap-delivery
    env_file:
      - ./config/local.env
    volumes:
      - ./:/var/www/html

  cheap-delivery-adm:
    image: mysql:8.1
    restart: always
    hostname: cheap-delivery-adm
    container_name: cheap-delivery-adm
    ports:
      - "3307:3306"
    environment:
      TZ: "America/Sao_Paulo"
      MYSQL_ROOT_PASSWORD: "root"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/mysql/config:/scripts/config
      - ./db/mysql/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  nginx:
    image: nginx:1.25-alpine
    restart: always
    container_name: nginx
    volumes:
      - ./public:/var/www/html
      - ./config/nginx/site.conf:/etc/nginx/conf.d/site.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.entrypoints=http"
      - "traefik.http.routers.nginx.rule=Host(`cheap-delivery.localhost`)"
    depends_on:
      - cheap-delivery

  reverse-proxy:
    image: traefik:3.0
    restart: always
    container_name: reverse-proxy
    command:
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.http.address=:80"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
      - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
